apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.service.name }}-web3auth
spec:
  secretStoreRef:
    name: fake
    kind: ClusterSecretStore
  target:
    name: {{ .Values.service.name }}-web3auth
  dataFrom:
  - extract:
      key: /web3auth
