# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: ghcr.io/cloudnativeentrepreneur/sveltekit-web3auth-template
  tag: v0.14.1
  pullPolicy: IfNotPresent
# define environment variables here as a map of key: value
env:
service:
  name: sveltekit-web3auth-template
  internalPort: 3000
knative:
  minScale: 1
  maxScale: 3
  concurrencyTarget: 100
local: false
probePath: /
livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  initialDelaySeconds: 0
  failureThreshold: 3
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
resources:
  limits:
    cpu: '1'
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 256Mi
