name: promote
on:
  push:
    tags:
    - v*.*.*

jobs:

  publish-container:
    uses: CloudNativeEntrepreneur/actions/.github/workflows/publish-container.yaml@main
    secrets: inherit

  promote-local:
    uses: CloudNativeEntrepreneur/actions/.github/workflows/gitops-promote-helm.yaml@main
    secrets: inherit
    with:
      environment_repository: CloudNativeEntrepreneur/example-local-env
      project: example-local-env
      pull_request: true
      name: example-ui
      values: |
        # Set from promote job of CloudNativeEntrepreneur/sveltekit-web3auth-template
        local: true

  promote-prod:
    uses: CloudNativeEntrepreneur/actions/.github/workflows/gitops-promote-helm.yaml@main
    secrets: inherit
    name: example-ui
    with:
      environment_repository: CloudNativeEntrepreneur/example-prod-env
      project: example-prod-env
      pull_request: true
